minib/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'minib.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^>>(?P<postNumber>\d+)', 'board.views.board'),
    url(r'^(?P<pageNumber>\d+)', 'board.views.board'),
    url(r'^', 'board.views.board', {'pageNumber': 1}),
)

board/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=30, blank=True, null=True, )
    #author = models.CharField(max_length=30, blank=True, null=True, )
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=1000)
    picURL = models.URLField(blank=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-id']

board/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms.CharField(required=False, label="Titolo")
    content = forms.CharField(widget=forms.Textarea, label="Contenuto (richiesto)")
    picURL = forms.URLField(required=False, label="Indirizzo dell'immagine")

board/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
#models
from board.models import *
#forms
from board.forms import *

posts_per_page = 5


def board(request, pageNumber=None, postNumber=None):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Post(
                title=cd['title'],
                content=cd['content'],
                picURL=cd['picURL'],
            ).save()
            return HttpResponseRedirect('/#lel')
    else:
        form = PostForm()

    totalposts = Post.objects.count()
    totalpages = totalposts//posts_per_page+2

    if postNumber:
        pageNumber = (totalposts-int(postNumber))//posts_per_page+1
        return HttpResponseRedirect('/' + str(pageNumber) + '#' + str(postNumber))

    lastpost = totalposts - (int(pageNumber)-1)*posts_per_page
    firstpost = lastpost - posts_per_page

    posts = Post.objects.filter(id__gte=firstpost, id__lte=lastpost)
    return render(request, 'board.html', {'form': form, 'posts': posts, 'currentPage':pageNumber, 'pages': range(1,totalpages), 'highlightedPost': postNumber, })

board/templates/board.html
{% load board_extras %}

<html>
<head>
    <title>MiniB</title>
</head>
<style type="text/css">
    body{
        background-color: ddf;
    }
    a{
        color: darkblue;}
    a:hover{
        color: blue;}
    textarea{
        #border: medium none;
        padding: 0px;
        margin: 0px;
        z-index: 6;
        left: 0px;
        outline: medium none;
        border-color: #77f;
        border-style: double;
        border-width: 1px;
    }
    #id_picURL{
        #border: medium none;
        padding: 0px;
        margin: 0px;
        z-index: 6;
        left: 0px;
        outline: medium none;
        border-color: #77f;
        border-style: double;
        border-width: 1px;
    }
    #id_title{
        #border: medium none;
        padding: 0px;
        margin: 0px;
        z-index: 6;
        left: 0px;
        outline: medium none;
        border-color: #77f;
        border-style: double;
        border-width: 1px;
    }
    .pages{
        color=red;
    }
    .post{
        border-radius: 10px;
		background-color: #c8ca2d;
        background-color: #ddddee;
		background-color:rgba(0,0,0,0.06);
        padding: 1em;
        padding-top: 1px;
        padding-bottom: 1px;
    }
    #content{
        background-color: #c8ca2d;
        background-color: #ddddee;
		background-color:rgba(0,0,0,0.06);
        margin: auto;
        width: 40em;
        padding: 2em;
        padding-top: 1em;
    }
    #invia{
        color: #FFF;
        background-color: #6AC065;
        padding: 5px 12px;
        font-size: 13px;
        line-height: 17px;
        min-width: 60px;
        display: inline-block;
        margin-bottom: 0px;
        font-weight: 400;
        text-align: center;
        vertical-align: middle;
        border: 1px solid transparent;
        white-space: nowrap;
    }
</style>
<body>

<div id="content">

<a href="/" style="text-align:center;"><h1>MiniB</h1></a>

<hr>
<form method="post" action="">
    {% csrf_token %}
    {% if form.errors %}
        <p style="color: red;">
            Per favore correggi gli errori qui sotto.
        </p>
    {% endif %}
    <table>
        {{ form.as_table }}
    </table>
    <input id="invia" type="submit" value="Invia">
</form>
<hr>

<span class="pages">
    Pagine (pagina corrente {{ currentPage }}):
    {% for pagenumber in pages %}
    <a href="/{{ pagenumber }}/">{{ pagenumber }}</a>
    {% endfor %}
</span>

<br>
<br>

<div id="posts">
    {% for post in posts %}
    <div class="post">
        <h4 class="postHeader">
            <a name="{{ post.id }}" href="/>>{{ post.id }}" >&gt;&gt;{{ post.id }}</a> -
            {{ post.title }}
        </h4>
        <hr>
         {% if post.picURL %}
             <a class="postThumbinail" href="{{ post.picURL }}"><img class="postThumbinail" alt="Immagine" src="http://quickthumbnail.com/resizepix.php?ez_orig=1&wm=&wm_size=16&wm_color=1filter=none&filename={{ post.picURL }}&width=250"></a>
		 {% endif %}

         {{ post.content|doublearrowquotes|urlize|linebreaks }}
    </div>
    <br>
    {% endfor %}
</div>

<span class="pages">
    Pagine (pagina corrente {{ currentPage }}):
    {% for pagenumber in pages %}
    <a href="/{{ pagenumber }}/">{{ pagenumber }}</a>
    {% endfor %}
</span>

</div>

<hr>
<footer>
<em>Powered by <a href="http://github.com/fgaz/miniB">MiniB</a></em>
</footer>

</body>
</html>